Multi agent models update
QuantEcon/lecture-julia.myst pull request #276
Opened 2023-10-10 23:34 UTC by annabellasd

2023-10-14 07:01 UTC, htrangtr requested changes
I tried to be as detailed as I could! I checked that:
- all unicodes are converted to text
- all outputs look good
- codes and comments are aligned so that it's easy to read.

I also checked to see if we can combine any functions in this set of lecture notes (aside from the lake model), but I couldn't find any. Since it's subjective, it would be great if you could go through them too.

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/aiyagari.md
> +    Q = setup_Q!(zeros(n, a_size, n), s_i_vals, z_chain)) = (; r, w, sigma, beta, z_chain, a_min, a_max, a_size, a_vals, z_size, n, s_vals, s_i_vals, u, R, Q)
space after (;

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/lake_model.md
> +function solve_mccall_model(mcm; U_iv = 1.0, V_iv = ones(length(mcm.w)), tol = 1e-5,iter = 2_000)
we might need a space before "iter"

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/lake_model.md
> +            w = range(10, 20, length = 60),         # w= wage values; E= distribution over wage values
Do you want to edit the comment to "w = wage values"? Also I think the part after "w = wage values" might belong to the code line below

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/markov_perf.md
> +Lamda1 = A - (B2 * F2)
I think this is "Lambda" but not sure if it's a different case for capital word - please let me know!

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/markov_perf.md
> +lq1 = QuantEcon.LQ(Q1, R1, Lamda1, B1, bet=beta)
same thing - not sure if it's "Lambda"

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/markov_perf.md
> +  @test Lamda1[1, 1] ≈ 1.0 && Lamda1[3, 2] ≈ -0.07584666305807419
Lambda

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/markov_perf.md
> +       0   delta_1   -delta_1 * b[2];
Do we want to realign the matrix columns here?

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/markov_perf.md
> +B1 = delta_1 * [1 -D[1, 1];
Do we want to realign the matrix columns here?

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/markov_perf.md
> +B2 = delta_1 * [0 -D[1, 2];
Do we want to realign the matrix columns here?

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/lucas_model.md
> +    return (gamma = gamma, beta = beta, alpha = alpha, sigma = sigma, phi = phi, grid = grid, shocks = shocks, h = h)
I think this can be `return (;gamma, beta, alpha, sigma, phi, grid, shocks, h)`. I tested that the code will run but please let me know if it's wrong

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/rational_expectations.md
> +     0 kappa1 kappa0
i think we might want to realign the matrix columns here too

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/uncertainty_traps.md
> +                    (;a, gamma_x, rho, sigma_theta, num_firms, sigma_F, c, mu_init, gamma_init, theta_init, sigma_x)
ok i don't see the comments being aligned in the original file but do we want align the comments here?

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/uncertainty_traps.md
> +        theta_old, gamma_old, mu_old, X_old, M_old = (df.theta[end], df.gamma[end], df.mu[end], df.X[end], df.M[end])
cb - not sure if need ;

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/aiyagari.md
>  r_vals = range(0.005, 0.04, length = 20)
double space on line 371 after `labels =` - I don't how to comment on it

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/schelling.md
> +##AT THIS ONE BUT LUCAS
this looks weird on the deployment. I'm sure u have your intention behind this but just want to highlight it in case this was a note-to-self that should be removed

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/arellano.md
> +                     theta = 0.282,    # prob of regaining access
I think the comments need to be aligned

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/arellano.md
> +    (;ygrid, ydefgrid, Bgrid, Pi, vf, vd, vc, policy, q, defprob) = ae
do you know why we cannot unpack in one line?

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/markov_perf.md
>      -a0 / 2.0     a1 / 2.0             a1]
I know columns are not aligned on the original version, but can you align them pls? it's hard to read when the columns are not straight

2023-10-14 07:01 UTC, htrangtr commented on lectures/multi_agent_models/lake_model.md
> +LakeModel(;lambda = 0.283, alpha = 0.013, b = 0.0124, d = 0.00822) = (;lambda, alpha, b, d)
I'm not sure why this doesn't look like the screenshot in the group chat. Is it a different PR?

2023-11-07 00:27 UTC, annabellasd commented on lectures/multi_agent_models/arellano.md
> +    (;ygrid, ydefgrid, Bgrid, Pi, vf, vd, vc, policy, q, defprob) = ae
no idea, maybe readability?

2023-11-07 00:28 UTC, annabellasd commented on lectures/multi_agent_models/lucas_model.md
> +    return (gamma = gamma, beta = beta, alpha = alpha, sigma = sigma, phi = phi, grid = grid, shocks = shocks, h = h)
yes thanks!

2023-11-07 06:01 UTC, htrangtr commented
Aside from `≉` symbol in schelling.md, everything else looks good

2023-11-09 09:34 UTC, htrangtr commented
Output error in Optimal Taxation without State-Contingent Debt - messaged you! Everything else looks good!

2024-01-04 08:01 UTC, merged