Dynamic programming squared update
QuantEcon/lecture-julia.myst pull request #277
Opened 2023-10-10 23:35 UTC by annabellasd

2023-10-14 17:06 UTC, htrangtr requested changes
I might need to go through this set of lecture notes again since many edits are needed. Some big edits are
- add "upsilon" to the formatter
- might need to "Tau" to the formatter - please see comments in "opt_tax_recur"
- some confusion between "xi" and "Xi"

As always, I checked that outputs look good. Basic unicode are beta, mu, etc are checked but
I might need to go through one more time for upsilon, Tau, xi and Xi.

***edited my comment - removed all points related to struct

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/dyn_stack.md
> +(;tol0, tol1, tol2) = defaultSettings
here the named tuples are created and then unpacked globally - will it make sense to not create the named tuples at all?

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/dyn_stack.md
> +model(;a0 = 10, a1 = 2, beta = 0.96, gamma = 120.,  n = 300) = (; a0, a1, beta, gamma, n)
double space in front of `n = 300`

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/dyn_stack.md
> +R_tilde = [0 0 0 0 -a0/2; 0 0 0 0 a1/2; 0 0 0 0 0; 0 0 0 0 0; -a0/2 a1/2 0 0 a1];
just a thought but I find this easier to read since it's a 5x5 matrix
`R_tilde = [0       0      0 0 -a0/2

                   0       0      0 0 a1/2

                   0       0      0 0 0

                   0       0      0 0 0

                  -a0/2 a1/2 0 0 a1]`
I don't know how to get this to format nicely but please let me know if you need clarification

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/dyn_stack.md
> +all((P  - ((R + F' * Q * F) + beta * (A - B * F)' * P * (A - B * F)) .< tol0))
double space after P

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/dyn_stack.md
>  R2 = [0 -a0/2 0; -a0/2 a1 a1/2; 0 a1/2 0];
It will look better if these look like a 3x3 matrix, but I also don't feel strongly about this since the matrices are small

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/dyn_stack.md
>  plot([vt_MPE, vt_leader, vt_follower], labels = ["MPE" "Stackelberg leader" "Stackelberg follower"],
in output, the legend is on top of the line -- maybe `legend = :outertopright`?

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
>      g, d, b, s = [dropdims(S * x, dims = 1) for S in (Sg, Sd, Sb, Ss)]
line 612 can be `(;Sg, Sd, Sb, Ss) = econ`

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
>      c = dropdims(Sc * x, dims = 1)
line 625 can be `(;Sg, Sd, Sb, Ss) = econ`

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
> +    In fact we solve for ν = lambda / (1 + 2*lambda).  Here ν is the
upsilon needs to be replaced here (4 in total - 2 on 616 + 2 on 617)

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
>      c = dropdims(Sc * x, dims = 1)
upsilon line 625, 628, 629, 630

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
>  function compute_ν(a0, b0)
upsilon

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
>          ν = 0.5 *(a0 - sqrt(disc)) / a0
upsilon

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
>  end
line 652, 657 -> upsilon

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
>      ν = compute_ν(a0, b0)
upsilon - 2 total

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
>      # Solve for the allocation given ν and x
upsilon

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
> +    Sc, Sl, c, l, p, tau, rvn = compute_allocation(econ, Sm, ν, x, b)
upsilon

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
>      ν = compute_ν(a0, b0)
upsilon

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
> +    Sc, Sl, c, l, p, tau, rvn = compute_allocation(econ, Sm, ν, x, b)
upsilon - 741, 742

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
>  function gen_fig_1(path)
you might want to specific legend position for all - legend covers graph for 2 outputs

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
> +    pi, Pi = compute_Pi(B, R, rvn, g,Xi)
xi not Xi? also space before xi

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
> +    pi, Pi = compute_Pi(B, R, rvn, g,Xi)
xi not Xi and space before xi

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
> +    Pi = cumsum(pi .*Xi)
Is this xi and not Xi?

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
> +   Xi = p[2:end] ./ temp[1:end-1]
same thing - xi?

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
> +    return (;g, d, b, s, c, l, p, tau, rvn, B, R, pi, Pi, Xi)
xi

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
> +   Xi = dropdims(Xi, dims = 1)
xi

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
> +    return(;g, d, b, s, c, l, p, tau, rvn, B, R, pi, Pi, Xi)
xi

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/lqramsey.md
> +    paths = [path.Xi, path.Pi]
xi

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/amss.md
>  end
ah same struct thing again. not sure if this might be a problem but if it is, we'll need to change the functions' arguments and unpack lines as well - please see my comments on lqramsey. It will be tricky for me to iterate all the changes here - might need to get my hands dirty with it. Please let me know if I can help

2023-10-14 17:06 UTC, htrangtr commented on format_myst.jl
> +    "P̃" => "P_tilde","F̃" => "F_tilde","d̃" => "d_tilde")
missing upsilon

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/amss.md
>  function Τ(model::Model, c::Union{Real,Vector}, n::Union{Real,Vector})
This T looks really much like a unicode on deployed - can you check this globally? may be "Tau"

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/amss.md
>      ΤHist = zeros(T)
same T here - looks like unicode

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/dyn_stack.md
> +R_tilde = [0 0 0 0 -a0/2; 0 0 0 0 a1/2; 0 0 0 0 0; 0 0 0 0 0; -a0/2 a1/2 0 0 a1];
i think this will be easier to read in the matrix format since it's 5x5, like
R_tilde = [0 0
                  2 1]

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/dyn_stack.md
> +(;tol0, tol1, tol2) = defaultSettings
here we create named tuples and then unpack it globally. i wonder if named tuples is even needed at all in this case?

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/dyn_stack.md
>  R = [0 -a0/2 0 0; -a0/2 a1 a1/2 0; 0 a1/2 0 0; 0 0 0 0];
i think this will be easier to read if it's in the form
R = [1 2 3
        4 5 6]

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/dyn_stack.md
>  R2 = [0 -a0/2 0; -a0/2 a1 a1/2; 0 a1/2 0];
I just feel like it'll be easier to read if the code looks like a matrix

2023-10-14 17:06 UTC, htrangtr commented on lectures/dynamic_programming_squared/dyn_stack.md
>  plot([vt_MPE, vt_leader, vt_follower], labels = ["MPE" "Stackelberg leader" "Stackelberg follower"],
the legend covers the graph here so you might want to add `legend = :outertopright`

2023-11-06 23:04 UTC, annabellasd commented on lectures/dynamic_programming_squared/dyn_stack.md
> +(;tol0, tol1, tol2) = defaultSettings
Maybe he wants it so its more explicit? But yea it would work to delete since we arent using the default Settings elsewhere.

2023-11-09 16:46 UTC, htrangtr commented
Output error in Optimal Taxation without State-Contingent Debt - messaged you! Everything else looks good!

2023-11-09 19:19 UTC, htrangtr commented
checked and looks good!

2024-01-04 19:07 UTC, merged